version: 2
# log-level: 3
# log-file: /home/jcom/efmlanserver.log
root-markers:
  - .ignore
  - .groovylintrc.json
  - .git/
  - .gitignore
lint-debounce: 3s

tools:
  groovylint: &npm-groovy-lint
    lint-command: 'npm-groovy-lint --output json --noserver ${INPUT} | jq -r -f %EFMLANGSERVER%/jq_filter.txt'
    lint-ignore-exit-code: true
    lint-stdin: true
    lint-offset-columns: 1
    lint-formats:
      - '%f  %l  %c  %tnfo  %m'
      - '%f  %l  %c  %tarning  %m'
      - '%f  %l  %c  %trror  %m'
    lint-category-map:
      i: I
      w: W
      e: E

languages:
  groovy:
    - <<: *npm-groovy-lint

  Jenkinsfile:
    - <<: *npm-groovy-lint
