# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

format = """
$os\
[](bg:#33658A fg:#FFFFFF)\
$directory\
[](fg:#33658A bg:#f28213)\
$git_branch\
$git_status\
[](fg:#f28213 bg:#33658A)\
$docker_context\
[ ](fg:#33658A)\
"""
# [](fg:#06969A bg:#33658A)\

right_format = """
$status\
[](fg:#ffffff bg:#000000)\
$cmd_duration
"""

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
format = '[  $symbol]($style)'
style = "bg:#FFFFFF fg:#000000"
disabled = false

[os.symbols]
AIX = " "
AlmaLinux = " "
Alpaquita = " "
Alpine = " "
ALTLinux = " "
Amazon = " "
Android = " "
AOSC = " "
Arch = " "
Artix = " "
Bluefin = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Elementary = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = " "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = " "
InstantOS = " "
Ios = "󰀷 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = " "
OpenCloudOS = " "
openEuler = " "
openSUSE = " "
OracleLinux = "󰺡 "
PikaOS = " "
Pop = " "
Raspbian = " "
Redhat = "󱄛 "
RedHatEnterprise = "󱄛 "
Redox = "󰀘 "
RockyLinux = " "
Solus = " "
SUSE = " "
Ubuntu = " "
Ultramarine = " "
Unknown = " "
Uos = " "
Void = " "
Windows = "󰍲 "
Zorin = " "

[directory]
style = "bg:#33658A"
format = "[  $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#f28213"
format = '[ $symbol $branch ]($style)'

[git_status]
conflicted = ''
ahead = '${count} '
behind = '${count} '
diverged = '${count}'
untracked = '${count} '
modified = '${count} '
staged = '${count} '
stashed = ''
deleted = '${count} '
style = "bg:#f28213"
format = '[$all_status$ahead_behind ]($style)'

[status]
disabled = false
style = 'bold green'
failure_style = 'bold red'
symbol = ''
success_symbol = ''
format = '[ $symbol $status ]($style)'

[cmd_duration]
format = '[ 󱦟 $duration ]($style)'
style = 'bg:#FFFFFF fg:#000000'
min_time = 500

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

[aws]
disabled = true

[azure]
disabled = true

[battery]
disabled = true

[line_break]
disabled = true

[gcloud]
disabled = true
